services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: unless-stopped
    environment:
      - SERVICES=sqs
      - DEBUG=1
    ports:
      - "4566:4566"

  worker:
    image: sqs-worker:latest
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ENDPOINT_URL_SQS=http://localstack:4566
      - LOG_LEVEL=DEBUG
      - QUEUE_URL=${QUEUE_URL}         # <<< pass-through from Make/ENV
    command: ["python", "app.py"]
